Secrets endpoints and encryption
tracehubpm/pmo pull request #52
Opened 2024-02-21 08:25 UTC by dukris

closes #51 
closes #50

---

## PR-Codex overview
This PR focuses on adding encryption functionality using Jasypt, updating SQL queries, and improving exception handling in GitHub platform tests.

### Detailed summary
- Added Jasypt encryption for secrets
- Updated SQL queries for better security
- Improved exception handling in GitHub platform tests

> The following files were skipped due to too many changes: `src/main/java/git/tracehub/pmo/secret/Keys.java`, `src/main/java/git/tracehub/pmo/secret/Key.java`, `src/test/java/it/database/DefaultSecretsIT.java`, `src/main/java/git/tracehub/pmo/secret/KeyOf.java`, `README.md`, `src/main/java/git/tracehub/pmo/secret/DefaultSecrets.java`, `src/test/java/git/tracehub/pmo/controller/TicketControllerTest.java`, `src/main/java/git/tracehub/pmo/secret/DefaultKeys.java`, `src/test/java/git/tracehub/pmo/controller/ProjectControllerTest.java`, `src/main/java/git/tracehub/pmo/secret/UniqueSecrets.java`, `src/main/java/git/tracehub/pmo/controller/SecretController.java`, `src/test/java/git/tracehub/pmo/secret/KeyOfTest.java`, `src/main/java/git/tracehub/pmo/secret/EncryptedSecrets.java`, `src/test/java/git/tracehub/pmo/extensions/MkArgumentException.java`, `src/test/java/it/database/DefaultKeysIT.java`, `src/test/java/it/web/RetrieveSecretsByProjectITCase.java`, `src/test/java/git/tracehub/pmo/secret/DefaultSecretsTest.java`, `src/test/java/git/tracehub/pmo/controller/AdviceControllerTest.java`, `src/test/java/git/tracehub/pmo/controller/SecretControllerTest.java`, `src/test/java/git/tracehub/pmo/secret/UniqueSecretsTest.java`, `src/test/java/git/tracehub/pmo/secret/EncryptedSecretsTest.java`, `src/test/java/git/tracehub/pmo/secret/DefaultKeysTest.java`, `src/test/java/it/web/UpdateSecretITCase.java`

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

2024-02-21 13:16 UTC, h1alexbel requested changes
@hizmailovich take a look, please

2024-02-21 13:16 UTC, h1alexbel commented on src/test/java/git/tracehub/pmo/controller/AdviceControllerTest.java
> +        Mockito.when(exception.getBindingResult()).thenReturn(result);
prefer [JUnit extensions](https://junit.org/junit5/docs/current/user-guide/) instead mock code duplication

2024-02-21 13:16 UTC, h1alexbel commented on src/test/resources/pre/sql/projects.sql
> +        'Iohe7UjU5MjHcxqsKk9vMLTlYHFCXHCLl4q0EjfBbfzmiYtXI1Vfw3KRUQEmbeVh')
lets document our `symetric` encryption approach we using here

2024-02-21 18:55 UTC, h1alexbel requested changes
@hizmailovich take a look, please

2024-02-21 18:55 UTC, h1alexbel commented on src/test/resources/pre/sql/projects.sql
> +-- value encrypted using algorithm PBEWithHMACSHA512AndAES_256
to document I mean to add useful information to our `README.md`

2024-02-23 15:30 UTC, h1alexbel commented
@hizmailovich please update your token

2024-02-23 15:47 UTC, h1alexbel approved these changes

2024-02-23 15:47 UTC, h1alexbel commented
@rultor merge

2024-02-23 15:49 UTC, hizmailovich commented
@rultor merge

2024-02-23 15:52 UTC, merged

2024-02-23 15:54 UTC, rultor commented
> @rultor merge

@hizmailovich Done! FYI, the full log is [here](https://www.rultor.com/t/38956-1961569774) (took me 3min)